module SiegeSiege
  class Siege
    CONFIGURATIONS = %w(
      verbose
      quiet
      gmethod
      csv
      timestamp
      fullurl
      display-id
      limit
      show-logfile
      logging
      logfile
      protocol
      chunked
      cache
      connection
      concurrent
      time
      reps
      file
      url
      delay
      timeout
      expire-session
      cookies
      failures
      internet
      benchmark
      user-agent
      accept-encoding
      url-escaping
      spinner
      login
      login-url
      ftp-login
      unique
      ssl-cert
      ssl-key
      ssl-timeout
      ssl-ciphers
      proxy-host
      proxy-port
      proxy-login
      follow-location
      zero-data-ok
    )

  end
end
